CREATE TABLE users (
                       id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(60) NULL DEFAULT NULL,
                       password VARCHAR(60) NULL DEFAULT NULL,
                       email VARCHAR(320) NULL DEFAULT NULL,
                       confirmation_token VARCHAR(256) NULL DEFAULT NULL,
                       role VARCHAR(20) NULL DEFAULT 'USER',
                       activated BOOLEAN DEFAULT FALSE

);

ALTER TABLE users ADD CONSTRAINT unique_username UNIQUE (username);

INSERT INTO users (username, password, email, role, activated) VALUEs ('Edvard Krainiy', '$2a$12$x4K16Kx.9aPY/hwndVpf5e9D30grq8p4b1QFxAiyqJ.JFUNq522WG', 'ekrayniy@inbox.ru', 'MANAGER', true);