CREATE TABLE operation
(
    id             BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id     BIGINT      NOT NULL,
    transaction_id BIGINT      NOT NULL,
    amount         DECIMAL,
    operation_type VARCHAR(20) NULL DEFAULT NULL
);