CREATE TABLE creation_request
(
    id            BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    payload       varchar(3200),
    status        varchar(20),
    created_id    BIGINT,
    creation_type VARCHAR(30)
);