CREATE TABLE transactions
(
    id        BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT      NOT NULL,
    issued_at TIMESTAMP,
    status    VARCHAR(40) NULL DEFAULT NULL
);